on:
  push:
jobs:
  commitChecking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: check commits length
        if: github.event.pusher.name == 'pouannes'
        run: |
          commitList=`git log --format=%B ${{ github.event.before }}...${{ github.event.after }}`
          flag=false
          while IFS= read -r line; do
              if [ ${#line} -ge 5 ]; then 
                  echo "line '$line' is greater than 5 chars"
              elif [ -z ${line} ]; then
                  echo "line '$line'  is empty"
              else 
                  echo "line '$line' is not long enough, setting the flag to true!"
                  flag=true
              fi
          done <<< "$commitList"
          echo "flag=$flag" >> $GITHUB_ENV
      - name: Trigger slack webhook
        if: env.flag == 'true'
        uses: indiesdev/curl@v1
        with:
          method: "POST"
          headers: '{ "Content-Type": "application/json" }'
          body: '{"text":"Hello, World!"}'
          # params: '{ "data": "'{"text":"Hello, World!"}'" }'
