on:
  push:
jobs:
  commitParsing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: get file changes
        run: |
          commitList=`git log --format=%B ${{ github.event.before }}...${{ github.event.after }}`
          while IFS= read -r line; do
              if [ ${#line} -ge 5 ] && [ ${#line} -eq 0]; then echo "line '$line' is greater than 5 chars"
              else echo "line '$line' is long enough"
              fi
          done <<< "$commitList"
