on:
  push:
jobs:
  commitParsing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: get file changes
        run: |
          commitList=`git log --format=%B ${{ github.event.before }}...${{ github.event.after }}`
          flag=false
          while IFS= read -r line; do
              if [ ${#line} -ge 5 ]; then 
                  echo "line '$line' is greater than 5 chars"
              elif [ -z ${line} ]; then
                  echo "line '$line'  is empty"
              else 
                  echo "line '$line' is not long enough, setting the flag to true!"
                  flag=true
              fi
          done <<< "$commitList"
          echo $flag
          if [ "$flag" = true ]; then
              echo "do the curl command"
          fi
