on:
  push:
jobs:
  commitParsing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: get file changes
        run: |
          commits=`git log --format=%B ${{ github.event.before }}...${{ github.event.after }}`
          echo $commits
